name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
# "Modify default permissions for GITHUB_TOKEN"
permissions:
  # "Work with the contents of the repository. For example, contents: read permits an action to list the
  #  commits, and contents: write allows the action to create a release."
  contents: read
  # "Work with GitHub Pages. For example, pages: write permits an action to request a GitHub Pages build."
  pages: write
  # "Fetch an OpenID Connect (OIDC) token. This requires id-token: write"
  id-token: write

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:
  build:
    name: Build & Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (${{ github.repository }})
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          cache: "npm"

      - name: npm ci
        run: npm ci

      - name: npm run compile
        run: npm run compile

      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./_site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
